name: accessible_text_view
description: A native iOS and Android Text View that improves accessibility of embedded links.
version: 1.0.0
homepage: https://dra11y.com
repository: https://github.com/dra11y/accessible_text_view

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  native_flutter_fonts: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dra11y.flutter.accessible_text_view
        pluginClass: AccessibleTextViewPlugin
      ios:
        pluginClass: AccessibleTextViewPlugin
